/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
    theme: {
        extend: {
            fontSize: {
                xs: ['0.75rem', { lineHeight: '1rem', letterSpacing: '-0.01em' }],
                sm: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.01em' }],
                base: ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em' }],
                lg: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
                xl: ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '2xl': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '6xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '7xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '8xl': ['5.25rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '9xl': ['6rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
            },
            fontFamily: {
                heading: '"Playfair Display", serif',
                paragraph: '"Inter", sans-serif',
                display: '"Playfair Display", serif',
                mono: 'ui-monospace, monospace'
            },
            colors: {
                primary: 'rgb(15 23 42 / <alpha-value>)',
                secondary: 'rgb(248 250 252 / <alpha-value>)',
                accent: 'rgb(34 197 94 / <alpha-value>)',
                background: 'rgb(248 250 252 / <alpha-value>)',
                foreground: 'rgb(15 23 42 / <alpha-value>)',
                link: 'rgb(34 197 94 / <alpha-value>)',
                'primary-foreground': 'rgb(255 255 255 / <alpha-value>)',
                'secondary-foreground': 'rgb(15 23 42 / <alpha-value>)',
                'accent-foreground': 'rgb(255 255 255 / <alpha-value>)',
                muted: 'rgb(241 245 249 / <alpha-value>)',
                'muted-foreground': 'rgb(100 116 139 / <alpha-value>)',
                card: 'rgb(255 255 255 / <alpha-value>)',
                'card-foreground': 'rgb(15 23 42 / <alpha-value>)',
                border: 'rgb(226 232 240 / <alpha-value>)',
                destructive: 'rgb(239 68 68 / <alpha-value>)',
                'destructive-foreground': 'rgb(255 255 255 / <alpha-value>)',
                input: 'rgb(226 232 240 / <alpha-value>)',
                ring: 'rgb(34 197 94 / <alpha-value>)',
                navy: '#0F172A',
                green: '#22C55E',
                teal: '#14B8A6',
            },
        },
    },
    future: {
        hoverOnlyWhenSupported: true,
    },
    plugins: [require('@tailwindcss/container-queries'), require('@tailwindcss/typography')],
}
